### ISSUE TITLE
Compatibility issue with the new Tidy5e sheet version

### ISSUE THREAD

**Issue by mech-tools** [VanirDev/VariantEncumbrance#19]
Hello,

Seems movement reduction is not working anymore with the newest version of Tidy5e

**Comment by VanirDev** [comment]
Would you mind elaborating further? The new update uses effect-based movement reductions, so you'll need to make sure that your sheet is displaying the new movement speeds instead of the deprecated dnd5e ones. If I remember correctly tidy5e has a toggle for switching between the two right above the speed value.

**Comment by mech-tools** [comment]
Yep, sorry, probably a small bug. After refresh, all is good 👍
