### ISSUE TITLE
VariantEncumbrance calculates from original data rather than derived data (DAE support)

### ISSUE THREAD

**Issue by Krigsmaskine** [VanirDev/VariantEncumbrance#30]
Trying to create a DAE feature that doubles the carrying capacity, it enables me to change the flag on the actor, I can read that it is changed, but the encumbrance value and the encumbrance percentage remains the same. 

The developer of DAE suggested the above, that VariantEncumbrance is calculating from original data rather than derived, and that is why it is not updating.

![image](https://user-images.githubusercontent.com/39592771/106735807-f8886700-6614-11eb-988c-e2931eeb6176.png)

**Comment by VanirDev** [comment]
This is intended to some degree. Due to the variant encumbrance rules all characters have their maximum encumbrance calculated from their strength. Third party effects have no impact on this calculation unless they are being used to directly affect the strength value. That being said, what you're trying to achieve is already possible without effects. As you're creating a character, you can use the "Powerful Build" special trait which will double the characters carrying capacity. Another slightly more granular way would be to add an effect which halves the encumbrance value itself. Any effects which directly modify the encumbrance.value property with an add or multiply are taken into account by VE. You could make an effect which multiplies encumbrance.value by 0.5 to get the effect you're looking for.

I may modify the VE system to allow effects to add and multiply the encumbrance max that VE calculated, but what you're looking for is still achievable in the current version.

**Comment by Krigsmaskine** [comment]
In this particular case, it was to have two mules' carrying capacity onto one single token, so the powerful build is already in effect and I ended up using this very workaround (multiplying by 0.5) you suggested. Thanks!

If it is possible, it would be appreciated! It would enable me to do more weight-related things like adding flat/subtracting flat values for spells and mechanics.

**Comment by p4535992** [comment]
Solved with v0.10.1
